# Generated by Django 3.0 on 2020-01-12 03:18

from django.conf import settings
from django.db import migrations, models
import fruitsApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='fruitsApp/images/uploaded_photos')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=models.SET(fruitsApp.models.get_admin_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
